version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 159823647
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - library_data:/var/lib/mysql

volumes:
  library_data:

